version: "3.8"
services:
  postgres:
    container_name: paperlessPostgresDev

    environment:
      FORCE_COLOR: 1

  redis:
    container_name: paperlessRedisDev

    environment:
      FORCE_COLOR: 1

  gotenberg:
    container_name: paperlessGotenbergDev

    environment:
      FORCE_COLOR: 1

  tika:
    container_name: paperlessTikaDev

    environment:
      FORCE_COLOR: 1

  paperless:
    container_name: paperlessDev

    environment:
      FORCE_COLOR: 1

    ports:
      - 3500:8000

  webdav:
    container_name: paperlessWebdavDev
    ports:
      - 3600:80

    environment:
      FORCE_COLOR: 1
      AUTH_TYPE: Digest