services:
  postgres:
    image: postgres:18.1-alpine
    restart: unless-stopped
    ports:
      - 5432

    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Missing environment variable see readme}
      POSTGRES_USER: paperless
      POSTGRES_DB: paperless

    volumes:
      - paperlessPostgressData:/var/lib/postgresql

  redis:
    image: redis:8.0-alpine
    restart: unless-stopped
    ports:
      - 6379

  gotenberg:
    image: gotenberg/gotenberg:8.24
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: apache/tika:3.2.3.0
    restart: unless-stopped

  paperless:
    image: paperlessngx/paperless-ngx:2.19
    restart: unless-stopped

    ports:
      - 8000

    environment:
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBHOST: postgres
      PAPERLESS_DBNAME: paperless
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: ${POSTGRES_PASSWORD?Missing environment variable see readme}
      PAPERLESS_OCR_LANGUAGE: deu+eng
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_FILENAME_FORMAT: "{{ owner_username }}/{{ created_year }}/{{ created_month }}/{{ correspondent }}/{{ asn }} - {{ title }}"
      PAPERLESS_CONSUMER_ENABLE_BARCODES: 1
      PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE: 1
      PAPERLESS_CONSUMER_INOTIFY_DELAY: 5

    volumes:
      - paperlessData:/usr/src/paperless/data
      - paperlessMedia:/usr/src/paperless/media
      - paperlessConsume:/usr/src/paperless/consume

    depends_on:
      - postgres
      - redis

  webdav:
    image: bytemark/webdav:2.4

    user: 1000:1000

    restart: unless-stopped

    environment:
      AUTH_TYPE: Basic
      USERNAME: ${PAPERLESS_WEBDAV_USER?Missing environment variable}
      PASSWORD: ${PAPERLESS_WEBDAV_PASSWORD?Missing environment variable}
      UID: 1000
      GID: 1000

    volumes:
      - paperlessWebdavLocks:/var/lib/dav
      - paperlessConsume:/var/lib/dav/data

volumes:
  paperlessData:
  paperlessMedia:
  paperlessPostgressData:
  paperlessConsume:
  paperlessWebdavLocks:
