---
    name: "Deploy service to production"

    on:
        release:
            types:
                - created

    jobs:
        deploy:
            uses: Beuterei/reusable-workflows/.github/workflows/deploy.yml@main
            with:
                environment_name: production
            secrets:
                SSH_HOST: ${{ secrets.SSH_PROD_HOST }}
                SSH_USERNAME: ${{ secrets.SSH_PROD_USERNAME }}
                SSH_KEY: ${{ secrets.SSH_PROD_KEY }}
                ENVIRONMENT: ${{ secrets.ENVIRONMENT }}